apiVersion: v1
kind: Service
metadata:
  name: sambaad-ext
  labels:
    app: samba-ad-service
spec:
  type: NodePort
  ports:
    - port: 88
      nodePort: 88
      name: "kerberos"
    - port: 88
      nodePort: 88
      protocol: UDP
      name: "kerberosu"
    - port: 389
      nodePort: 389
      name: "ldap"
    - port: 636
      nodePort: 636
      name: "ldaps"
  selector:
    app: samba-ad
